version: "3.7"
services:
  reverse-proxy:
    container_name: wdg-reverse-proxy
    image: traefik
    command: --api --docker
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - "proxy-network"
      - "dmz-external-network"
    ports:
      - "8020:80"
      - "8080:8080"
    labels:
      - "traefik.frontend.rule=Host:traefik.local"
      - "traefik.docker.network:proxy-network"
      - "traefik.port=8080"
      - "traefik.enable=false"

  mailhog:
    container_name: wdg-mailhog
    image: mailhog/mailhog
    networks:
      - "dmz-external-network"
      - "proxy-network"
    ports:
      - "${MAILHOG_PORT}:8025"
    labels:
      - "traefik.docker.network=dmz-external-network"
      - "traefik.frontend.rule=Host:mailhog.local"
      - "traefik.port=8025"

  laravel:
    container_name: wdg-nova
    build:
      context: ./config/laravel
      dockerfile: Dockerfile
    volumes:
      - "../:/app"
      - "laravel-node-modules:/app/node_modules"
    environment:
      DB_PORT: ${DB_PORT}
      DB_HOST: database
    networks:
      - "dmz-external-network"
      - "proxy-network"
    ports:
      - "${LARAVEL_PORT}:80"
    depends_on:
      - database
    labels:
      - "traefik.docker.network=dmz-external-network"
      - "traefik.backend=laravel"
      - "traefik.frontend.rule=Host:laravel.local"
      - "traefik.port=80"

  database:
    container_name: wdg-database
    image: mariadb:10.4
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - "dmz-external-network"
    ports:
      - "${DATABASE_PORT}:3306"
    labels:
      - "traefik.enable=false"

  swagger-ui:
    container_name: wdg-swagger-ui
    image: swaggerapi/swagger-ui
    networks:
      - "proxy-network"
    environment:
      SWAGGER_JSON: /docs/api.json
    volumes:
      - ../docs:/docs
    ports:
      - "${SWAGGER_PORT}:8080"
    labels:
      - "traefik.docker.network=proxy-network"
      - "traefik.backend=swagger"
      - "traefik.frontend.rule=Host:swagger.local"
      - "traefik.port=8080"

networks:
  dmz-external-network:
  proxy-network:

volumes:
  db-data:
  laravel-node-modules:
