#!/bin/sh

# apt-get update 
# apt-get install curl

ERROR_CODE=1

while [ "$ERROR_CODE" != "0" ]
do
    sleep 1
    echo "Waiting App"
    curl -f http://sls-gd-app
    ERROR_CODE=$?
done

nginx -g 'daemon off;'
